server:
  port: 9080
  servlet.context-path: /api/v1


spring:
  jackson:
    serialization:
      write-dates-as-timestamps: true
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
  main:
    allow-bean-definition-overriding: true
    
#springdoc:
#  swagger-ui:
#    disable-swagger-default-url: true
#    urls[0]:
#      name: 'Auth service'
#      url: '/v1/api-docs'    



service:
  properties:
    version: v1.0
    terms-of-service-url: http://swagger.io/terms/
    license-name: Apache 2.0
    license-url: http://springdoc.org


